# Generated by Django 3.2.16 on 2023-10-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
        ('clients', '0001_initial'),
        ('factures', '0002_facture_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='produits',
            field=models.ManyToManyField(related_name='factures', through='factures.LigneFacture', to='products.Product'),
        ),
    ]
