# Generated by Django 3.2.16 on 2024-01-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_auto_20231010_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='payments',
        ),
    ]
