# Generated by Django 3.2.16 on 2024-01-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20240120_1833'),
        ('factures', '0004_remove_facture_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='facture_payments', to='payment.Payment'),
        ),
    ]
